// Parses and validates a benchmark flower at the trust boundary: a file dropped
// into `flowers/`. Each flower is one SVG generated by an LLM; the header
// comment records the benchmark data (which model, who ran it, the prompt used,
// and the author's notes on the process). This module is pure and deterministic — it is the
// mutation-testing target (see stryker.conf.json) and the guard the CI
// contribution check (tests/flowers.test.ts) relies on.

export interface Flower {
  id: string;
  name: string;
  author: string;
  model: string;
  prompt: string;
  comment: string;
  github?: string;
  svg: string;
}

export type ParseResult = { ok: true; flower: Flower } | { ok: false; errors: string[] };

const REQUIRED_TEXT_FIELDS = ['name', 'author', 'model', 'prompt', 'comment'] as const;

// Heuristic denylist for the most common ways an SVG becomes an XSS vector once
// inlined into the page. Contributions are also human-reviewed on every PR.
// ponytail: denylist, not a parser — covers the common vectors, not every one
// (e.g. <use> to an external doc). Swap for DOMPurify if untrusted SVGs ever
// bypass PR review.
const DISALLOWED: ReadonlyArray<{ pattern: RegExp; error: string }> = [
  { pattern: /<script[\s>]/i, error: 'disallowed content: <script> tag' },
  { pattern: /\son[a-z]+\s*=/i, error: 'disallowed content: inline event handler' },
  { pattern: /javascript:/i, error: 'disallowed content: javascript: URI' },
];

const METADATA_COMMENT = /<!--([\s\S]*?)-->/;
const SVG_ELEMENT = /<svg[\s>]/i;

// A flower is drawn top-down on a fixed 255x255 canvas so the field stays
// uniform. The viewBox is the checkable half of that contract ("seen from
// above" is a design guideline we can't verify).
const REQUIRED_VIEWBOX = /viewBox\s*=\s*["']\s*0\s+0\s+255\s+255\s*["']/i;

function parseHeader(source: string): Record<string, string> {
  const match = METADATA_COMMENT.exec(source);
  if (!match) return {};

  const fields: Record<string, string> = {};
  for (const line of match[1].split('\n')) {
    const separator = line.indexOf(':');
    if (separator === -1) continue;
    const key = line.slice(0, separator).trim().toLowerCase();
    const value = line.slice(separator + 1).trim();
    if (key && value) fields[key] = value;
  }
  return fields;
}

export function parseFlower(id: string, source: string): ParseResult {
  const fields = parseHeader(source);
  const errors: string[] = [];

  for (const field of REQUIRED_TEXT_FIELDS) {
    if (!fields[field]) errors.push(`missing required field: ${field}`);
  }

  if (!SVG_ELEMENT.test(source)) errors.push('no <svg> element found');

  if (!REQUIRED_VIEWBOX.test(source)) errors.push('svg must declare viewBox="0 0 255 255"');

  for (const { pattern, error } of DISALLOWED) {
    if (pattern.test(source)) errors.push(error);
  }

  if (errors.length > 0) return { ok: false, errors };

  return {
    ok: true,
    flower: {
      id,
      name: fields.name,
      author: fields.author,
      model: fields.model,
      prompt: fields.prompt,
      comment: fields.comment,
      ...(fields.github ? { github: fields.github } : {}),
      svg: source,
    },
  };
}
